# Generated by Django 2.1.7 on 2019-03-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=8)),
                ('contact', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
